theme: beautiful-jekyll-theme
# Specify remote theme so github pages can load it from the author's repository
remote_theme: daattali/beautiful-jekyll
navbar-links: 
  Home: "/"
  API Documentation:
    - Downtime Database: "/docs/downtime.html"
