# Specify remote theme so github pages can load it from the author's repository
remote_theme: chrisrhymes/bulma-clean-theme
# theme: bulma-clean-theme
title: Observatory Control System
baseurl: "/"
url: "https://eheinrich.github.io/observatorycontrolsystem.github.io/"
